# Generated by Django 4.0.7 on 2022-11-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesseeregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='lessoregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Company_name', models.CharField(max_length=30)),
                ('Company_profile', models.FileField(upload_to='')),
                ('Country', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
