# Generated by Django 4.0.7 on 2022-11-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0003_james'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesseeregister',
            name='Phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
