# Generated by Django 4.0.7 on 2022-11-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0004_alter_lesseeregister_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lessoregister',
            new_name='lessorregister',
        ),
    ]
