# Generated by Django 4.0.7 on 2022-11-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0005_rename_lessoregister_lessorregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='james',
            old_name='Email',
            new_name='Email_id',
        ),
        migrations.RenameField(
            model_name='lesseeregister',
            old_name='Email',
            new_name='Email_id',
        ),
        migrations.RenameField(
            model_name='lessorregister',
            old_name='Email',
            new_name='Email_id',
        ),
    ]
