# Generated by Django 4.0.7 on 2022-11-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0006_rename_email_james_email_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lesseeregister',
            new_name='register',
        ),
        migrations.DeleteModel(
            name='james',
        ),
        migrations.DeleteModel(
            name='lessorregister',
        ),
    ]
