# Generated by Django 4.0.7 on 2022-11-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0010_rename_company_name_register_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessorregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Company_name', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Email_id', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
