# Generated by Django 4.0.7 on 2022-11-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0011_lessorregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lessorregister',
            new_name='lessor',
        ),
    ]
