# Generated by Django 4.0.7 on 2022-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0012_rename_lessorregister_lessor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='Designation',
        ),
        migrations.AddField(
            model_name='upload',
            name='Container_condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='Container_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='Container_length',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='Container_material',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='Container_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='Description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='Location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='Rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
