# Generated by Django 4.0.7 on 2022-11-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0013_remove_upload_designation_upload_container_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Container_condition',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Container_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Container_length',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Container_material',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Container_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Rate',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
