# Generated by Django 4.0.7 on 2022-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0015_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Owner',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
