# Generated by Django 4.0.7 on 2022-12-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0016_upload_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, null=True)),
                ('Company_name', models.CharField(max_length=40, null=True)),
                ('Company_address', models.CharField(max_length=100, null=True)),
                ('Shipping_Address', models.CharField(max_length=100, null=True)),
                ('Phone_no', models.CharField(max_length=40, null=True)),
                ('Email', models.CharField(max_length=40, null=True)),
                ('Owner', models.CharField(max_length=40, null=True)),
                ('Container_id', models.CharField(max_length=100, null=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
