# Generated by Django 4.0.7 on 2022-12-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0017_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Owner',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
