# Generated by Django 4.0.7 on 2022-12-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0018_alter_book_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Shipping_Address',
            new_name='Shipping_Location',
        ),
    ]
