# Generated by Django 4.0.7 on 2022-12-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0020_rename_shipping_location_book_shipping_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='wner',
            field=models.DateTimeField(max_length=40, null=True),
        ),
    ]
